net: davinci_cpdma: export required symbol for other module builds to pass
Without this patch davinci-emac driver module build fails with below
error:
ERROR: "cpdma_chan_process" [drivers/net/ethernet/ti/davinci_emac.ko]
undefined!
ERROR: "cpdma_chan_create" [drivers/net/ethernet/ti/davinci_emac.ko]
undefined!
ERROR: "cpdma_ctlr_create" [drivers/net/ethernet/ti/davinci_emac.ko]
undefined!
ERROR: "cpdma_chan_start" [drivers/net/ethernet/ti/davinci_emac.ko]
undefined!
ERROR: "cpdma_chan_stop" [drivers/net/ethernet/ti/davinci_emac.ko]
undefined!
ERROR: "cpdma_ctlr_destroy" [drivers/net/ethernet/ti/davinci_emac.ko]
undefined!
ERROR: "cpdma_chan_destroy" [drivers/net/ethernet/ti/davinci_emac.ko]
undefined!
ERROR: "cpdma_ctlr_stop" [drivers/net/ethernet/ti/davinci_emac.ko]
undefined!
ERROR: "cpdma_ctlr_start" [drivers/net/ethernet/ti/davinci_emac.ko]
undefined!
ERROR: "cpdma_chan_submit" [drivers/net/ethernet/ti/davinci_emac.ko]
undefined!
ERROR: "cpdma_ctlr_dump" [drivers/net/ethernet/ti/davinci_emac.ko]
undefined!

Signed-off-by: Manjunathappa, Prakash <prakash.pm@ti.com>